name: npm-release
on:
  push:
    branches:
      - release
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    name: release
    env:
      MY_SECRET   : ${{secrets.BYCNTCHEN}}
      USER_NAME   : githubaction
      USER_EMAIL  : githubaction@fake.com
      NPM_TOKEN   : ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: standard-version
      run: |
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git checkout -b release
        npm run release
    - name: push banch
      run: |
        git remote set-url origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
        git push origin -u release
    - name: npm publish
      run: |
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        npm publish
    - name: merge master
      run: |
         git checkout master
         git merge release
         git push origin -u master
